name: Android Robot Framework Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-appiumlibrary
        pip install robotframework-requests

    - name: Start Android Emulator and Run Tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        profile: Nexus 5
        emulator-options: -no-window -no-audio -gpu swiftshader_indirect -no-snapshot-save -no-boot-anim
        disable-animations: true
        boot-timeout-minutes: 10
        script: |
          adb devices
          adb install $GITHUB_WORKSPACE/non_mfi_build.apk
          # Optionally, get the emulator device name for your test
          export DEVICE_NAME=$(adb devices | grep emulator | head -1 | cut -f1)
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          sed -i "s/emulator-5554/$DEVICE_NAME/g" $GITHUB_WORKSPACE/TEST/test.robot
          # Start Appium
          npm install -g appium@2.0.0
          npm install -g appium-uiautomator2-driver
          nohup appium --base-path /wd/hub > /dev/null 2>&1 &
          sleep 10
          # Run Robot Framework tests
          cd $GITHUB_WORKSPACE/TEST
          robot --outputdir ../results --timestampoutputs test.robot

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results
        path: |
          results/
          report.html
          log.html
          output.xml
        retention-days: 30

    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          try {
            const outputPath = path.join(process.env.GITHUB_WORKSPACE, 'results', 'output.xml');
            if (fs.existsSync(outputPath)) {
              const output = fs.readFileSync(outputPath, 'utf8');
              const totalTests = (output.match(/tests="(\\d+)"/) || [])[1] || 0;
              const failedTests = (output.match(/failures="(\\d+)"/) || [])[1] || 0;
              const passedTests = parseInt(totalTests) - parseInt(failedTests);
              const comment = `## 🤖 Robot Framework Test Results